// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockAPI.Models;

#nullable disable

namespace StockAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221209212604_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockAPI.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 100,
                            CreatedDate = new DateTime(2022, 12, 10, 0, 26, 4, 336, DateTimeKind.Local).AddTicks(1209),
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Count = 100,
                            CreatedDate = new DateTime(2022, 12, 10, 0, 26, 4, 336, DateTimeKind.Local).AddTicks(1210),
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            Count = 100,
                            CreatedDate = new DateTime(2022, 12, 10, 0, 26, 4, 336, DateTimeKind.Local).AddTicks(1211),
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            Count = 100,
                            CreatedDate = new DateTime(2022, 12, 10, 0, 26, 4, 336, DateTimeKind.Local).AddTicks(1212),
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            Count = 100,
                            CreatedDate = new DateTime(2022, 12, 10, 0, 26, 4, 336, DateTimeKind.Local).AddTicks(1213),
                            ProductId = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
